/* Örnek içerik — yapı ve akış denemek için hazırlanmış küçük bir set.
   Gerçek içerik (16.066 soru, 981 kart, 113 konu, 32 deneme) Android
   uygulamasından `npm run import:assets` ile aktarılır ve bu dosyaların
   yerini alır. */

export const DERSLER = [
  { id: 'turkce', ad: 'Türkçe', grup: 'gy', ikon: 'turkce', renk: '#2a78d6', renkKoyu: '#3987e5' },
  { id: 'matematik', ad: 'Matematik', grup: 'gy', ikon: 'matematik', renk: '#eb6834', renkKoyu: '#d95926' },
  { id: 'tarih', ad: 'Tarih', grup: 'gk', ikon: 'tarih', renk: '#1baf7a', renkKoyu: '#199e70' },
  { id: 'cografya', ad: 'Coğrafya', grup: 'gk', ikon: 'cografya', renk: '#eda100', renkKoyu: '#c98500' },
  { id: 'vatandaslik', ad: 'Vatandaşlık', grup: 'gk', ikon: 'vatandaslik', renk: '#e87ba4', renkKoyu: '#d55181' },
  { id: 'guncel', ad: 'Güncel Bilgiler', grup: 'gk', ikon: 'guncel', renk: '#008300', renkKoyu: '#008300' },
  { id: 'egitimbilimleri', ad: 'Eğitim Bilimleri', grup: 'eb', ikon: 'egitimbilimleri', renk: '#4a3aa7', renkKoyu: '#9085e9' },
]

export const KONULAR = [
  // Türkçe
  ['turkce', 'ses-bilgisi', 'Ses Bilgisi'],
  ['turkce', 'yazim-kurallari', 'Yazım Kuralları'],
  ['turkce', 'noktalama', 'Noktalama İşaretleri'],
  ['turkce', 'sozcukte-anlam', 'Sözcükte Anlam'],
  ['turkce', 'cumlede-anlam', 'Cümlede Anlam'],
  ['turkce', 'paragraf', 'Paragraf'],
  ['turkce', 'cumlenin-ogeleri', 'Cümlenin Ögeleri'],
  ['turkce', 'anlatim-bozuklugu', 'Anlatım Bozuklukları'],
  // Matematik
  ['matematik', 'temel-kavramlar', 'Temel Kavramlar'],
  ['matematik', 'bolunebilme', 'Bölme ve Bölünebilme'],
  ['matematik', 'ebob-ekok', 'EBOB - EKOK'],
  ['matematik', 'oran-oranti', 'Oran - Orantı'],
  ['matematik', 'problemler', 'Problemler'],
  ['matematik', 'kumeler', 'Kümeler'],
  ['matematik', 'olasilik', 'Permütasyon, Kombinasyon, Olasılık'],
  ['matematik', 'geometri', 'Geometri'],
  // Tarih
  ['tarih', 'islamiyet-oncesi', 'İslamiyet Öncesi Türk Tarihi'],
  ['tarih', 'ilk-turk-islam', 'İlk Türk-İslam Devletleri'],
  ['tarih', 'osmanli-kurulus', 'Osmanlı Kuruluş Dönemi'],
  ['tarih', 'osmanli-yukselme', 'Osmanlı Yükselme Dönemi'],
  ['tarih', 'osmanli-dagilma', 'Osmanlı Dağılma Dönemi'],
  ['tarih', 'kurtulus-savasi', 'Kurtuluş Savaşı'],
  ['tarih', 'inkilaplar', 'Atatürk İnkılapları'],
  ['tarih', 'ataturk-ilkeleri', 'Atatürk İlkeleri'],
  // Coğrafya
  ['cografya', 'cografi-konum', 'Türkiye’nin Coğrafi Konumu'],
  ['cografya', 'yer-sekilleri', 'Yer Şekilleri'],
  ['cografya', 'iklim', 'İklim ve Bitki Örtüsü'],
  ['cografya', 'nufus-yerlesme', 'Nüfus ve Yerleşme'],
  ['cografya', 'tarim-hayvancilik', 'Tarım ve Hayvancılık'],
  ['cografya', 'madenler-enerji', 'Madenler ve Enerji'],
  ['cografya', 'ulasim-turizm', 'Ulaşım, Ticaret ve Turizm'],
  // Vatandaşlık
  ['vatandaslik', 'hukuk-baslangic', 'Hukukun Temel Kavramları'],
  ['vatandaslik', 'anayasa-tarihi', 'Türk Anayasa Tarihi'],
  ['vatandaslik', 'temel-haklar', 'Temel Hak ve Hürriyetler'],
  ['vatandaslik', 'yasama', 'Yasama'],
  ['vatandaslik', 'yurutme', 'Yürütme'],
  ['vatandaslik', 'yargi', 'Yargı'],
  ['vatandaslik', 'idare', 'İdare Hukuku'],
  // Güncel
  ['guncel', 'kuruluslar', 'Uluslararası Kuruluşlar'],
  ['guncel', 'kultur-sanat', 'Kültür, Sanat ve Spor'],
  ['guncel', 'turkiye-guncel', 'Türkiye’den Güncel Bilgiler'],
  // Eğitim Bilimleri
  ['egitimbilimleri', 'gelisim', 'Gelişim Psikolojisi'],
  ['egitimbilimleri', 'ogrenme', 'Öğrenme Psikolojisi'],
  ['egitimbilimleri', 'program', 'Program Geliştirme'],
  ['egitimbilimleri', 'yontem-teknik', 'Öğretim Yöntem ve Teknikleri'],
  ['egitimbilimleri', 'olcme', 'Ölçme ve Değerlendirme'],
  ['egitimbilimleri', 'rehberlik', 'Rehberlik'],
  ['egitimbilimleri', 'sinif-yonetimi', 'Sınıf Yönetimi'],
]

/* [konuId, soru, [şıklar], doğruIndeks, açıklama] */
export const SORULAR = [
  // ---- TÜRKÇE ----
  ['ses-bilgisi', 'Aşağıdaki sözcüklerin hangisinde ünsüz yumuşaması (ünsüz değişimi) vardır?',
    ['kitabı', 'sokak', 'yaprak', 'çiçek', 'kalem'], 0,
    '"Kitap" sözcüğü ünlüyle başlayan bir ek aldığında sondaki "p" sesi "b"ye dönüşür: kitap → kitabı.'],
  ['ses-bilgisi', '"Burnu, ağzı, oğlu" sözcüklerinde görülen ses olayı aşağıdakilerden hangisidir?',
    ['Ünlü türemesi', 'Ünlü düşmesi', 'Ünsüz türemesi', 'Ünsüz benzeşmesi', 'Ulama'], 1,
    'Burun → burnu, ağız → ağzı, oğul → oğlu örneklerinde ikinci hecedeki dar ünlü düşmüştür.'],
  ['yazim-kurallari', 'Aşağıdaki cümlelerin hangisinde yazım yanlışı vardır?',
    ['Herkes yarın erken gelecek.', 'Yalnız kalmaktan hoşlanmıyor.', 'Hiçbir şey söylemedi.', 'Bir kaç gün sonra döneriz.', 'Ancak o zaman anlarsın.'], 3,
    '"Birkaç" bitişik yazılır. "Bir kaç" biçiminde ayrı yazılması yanlıştır.'],
  ['noktalama', '"Bugün hava çok güzel ( ) hadi pikniğe gidelim ( )" cümlesinde parantezle gösterilen yerlere sırasıyla hangi noktalama işaretleri getirilmelidir?',
    ['virgül - nokta', 'noktalı virgül - ünlem', 'iki nokta - soru işareti', 'virgül - üç nokta', 'nokta - nokta'], 1,
    'Anlamca birbirine bağlı ancak bağlaç kullanılmadan sıralanmış cümleler noktalı virgülle ayrılır; seslenme/coşku bildiren cümlenin sonuna ünlem konur.'],
  ['sozcukte-anlam', '"Ağır" sözcüğü aşağıdaki cümlelerin hangisinde "ciddi, önemli" anlamında kullanılmıştır?',
    ['Valizi çok ağırdı.', 'Ağır bir hastalık geçirdi.', 'Ağır ağır yürüyordu.', 'Yemekler biraz ağır olmuş.', 'Ağır bir koku vardı odada.'], 1,
    '"Ağır bir hastalık" tamlamasında sözcük "ciddi, tehlikeli" anlamındadır.'],
  ['cumlede-anlam', 'Aşağıdaki cümlelerin hangisinde "koşul (şart)" anlamı vardır?',
    ['Çalışırsan kazanırsın.', 'Çok çalıştı ama kazanamadı.', 'Yağmur yağdığı için gelemedi.', 'Hem çalıştı hem kazandı.', 'Sanırım yarın gelir.'], 0,
    '"-sa / -se" eki ya da "ancak, yeter ki" gibi sözcükler koşul anlamı katar: "Çalışırsan kazanırsın."'],
  ['cumlenin-ogeleri', '"Yaşlı adam, torununa masal anlatıyordu." cümlesinde "torununa" sözcüğü cümlenin hangi ögesidir?',
    ['Özne', 'Belirtili nesne', 'Dolaylı tümleç', 'Zarf tümleci', 'Yüklem'], 2,
    '"Kime anlatıyordu?" sorusunun cevabı olan "torununa" yönelme durumundadır ve dolaylı tümleçtir.'],
  ['anlatim-bozuklugu', 'Aşağıdaki cümlelerin hangisinde gereksiz sözcük kullanımından kaynaklanan anlatım bozukluğu vardır?',
    ['Yukarıya doğru yukarı çıktı.', 'Kitabı dün okudum.', 'Erken gelmesini istedim.', 'Onu görünce sevindim.', 'Yarın toplantı var.'], 0,
    '"Yukarı çıkmak" ifadesinde "yukarıya doğru" sözü gereksizdir; anlam zaten sözcükte vardır.'],
  ['paragraf', 'Bir paragrafta "ana düşünce" için aşağıdakilerden hangisi söylenebilir?',
    ['Paragrafta en çok tekrar eden sözcüktür.', 'Yazarın okura iletmek istediği temel yargıdır.', 'Her zaman ilk cümlede yer alır.', 'Paragrafın uzunluğunu belirler.', 'Yardımcı düşüncelerin toplamıdır.'], 1,
    'Ana düşünce, yazarın paragrafı yazma amacını taşıyan temel yargıdır; paragrafın herhangi bir yerinde yer alabilir ya da sezdirilebilir.'],

  // ---- MATEMATİK ----
  ['temel-kavramlar', 'Ardışık üç tek sayının toplamı 45 ise, bu sayıların en büyüğü kaçtır?',
    ['13', '15', '17', '19', '21'], 2,
    'Sayılar x-2, x, x+2 olsun. Toplam 3x = 45 → x = 15. En büyüğü x+2 = 17’dir.'],
  ['bolunebilme', '3AB4 dört basamaklı sayısı 9 ile tam bölünebiliyorsa, A + B toplamının alabileceği en küçük değer kaçtır?',
    ['0', '2', '5', '7', '9'], 1,
    'Rakamlar toplamı 3+A+B+4 = 7+A+B, 9’un katı olmalıdır. En küçük uygun değer 9’dur → A+B = 2.'],
  ['ebob-ekok', 'Boyutları 24 cm ve 36 cm olan dikdörtgen bir karton, artık kalmayacak biçimde eş karelere ayrılacaktır. Karelerin bir kenarı en fazla kaç cm olabilir?',
    ['4', '6', '8', '12', '18'], 3,
    'En büyük kare kenarı EBOB(24, 36) = 12 cm’dir.'],
  ['oran-oranti', 'Bir işi A işçisi 12 günde, B işçisi 6 günde bitiriyor. İkisi birlikte çalışırsa iş kaç günde biter?',
    ['3', '4', '5', '6', '8'], 1,
    'Birim zamanda A 1/12, B 1/6 iş yapar. Toplam 1/12 + 2/12 = 3/12 = 1/4 → iş 4 günde biter.'],
  ['problemler', 'Bir sınıftaki öğrencilerin %60’ı kızdır. Sınıfta 12 erkek öğrenci olduğuna göre sınıf mevcudu kaçtır?',
    ['20', '24', '28', '30', '32'], 3,
    'Erkekler toplamın %40’ıdır. 0,40·x = 12 → x = 30.'],
  ['problemler', 'Bir malın fiyatı önce %20 artırılıyor, sonra yeni fiyat üzerinden %20 indiriliyor. Son fiyat ilk fiyata göre nasıl değişmiştir?',
    ['%4 artmıştır', 'Değişmemiştir', '%4 azalmıştır', '%2 azalmıştır', '%1 artmıştır'], 2,
    '100 → 120 → 120·0,80 = 96. İlk fiyata göre %4 azalmıştır.'],
  ['kumeler', 'A ve B kümeleri için s(A) = 12, s(B) = 9 ve s(A∩B) = 4 ise s(A∪B) kaçtır?',
    ['15', '16', '17', '21', '25'], 2,
    's(A∪B) = s(A) + s(B) − s(A∩B) = 12 + 9 − 4 = 17.'],
  ['olasilik', 'Bir torbada 4 kırmızı, 6 mavi bilye vardır. Rastgele çekilen bir bilyenin kırmızı olma olasılığı kaçtır?',
    ['1/5', '2/5', '1/2', '3/5', '2/3'], 1,
    'İstenen durum / tüm durumlar = 4/10 = 2/5.'],
  ['geometri', 'Bir üçgenin iç açılarının ölçüleri 2x, 3x ve 4x ise en büyük açının ölçüsü kaç derecedir?',
    ['40', '60', '70', '80', '90'], 3,
    '2x + 3x + 4x = 180 → 9x = 180 → x = 20. En büyük açı 4x = 80°.'],

  // ---- TARİH ----
  ['islamiyet-oncesi', 'Türk adının geçtiği ilk Türk devleti aşağıdakilerden hangisidir?',
    ['Asya Hun Devleti', 'Göktürk (Kök Türk) Devleti', 'Uygur Devleti', 'Avar Devleti', 'Kırgız Devleti'], 1,
    'Türk adını devlet adı olarak kullanan ilk devlet Göktürk Devleti’dir (552).'],
  ['islamiyet-oncesi', 'Orhun Yazıtları hangi dönemde dikilmiştir?',
    ['Asya Hunları', 'I. Göktürk Devleti', 'II. Göktürk (Kutluk) Devleti', 'Uygurlar', 'Hazarlar'], 2,
    'Orhun (Göktürk) Yazıtları, II. Göktürk (Kutluk) Devleti döneminde 8. yüzyılda dikilmiştir.'],
  ['ilk-turk-islam', 'Malazgirt Savaşı hangi yıl ve hangi devletler arasında yapılmıştır?',
    ['1040 - Gazneliler ve Selçuklular', '1071 - Büyük Selçuklu ve Bizans', '1176 - Anadolu Selçuklu ve Bizans', '1243 - Anadolu Selçuklu ve Moğollar', '1048 - Selçuklu ve Bizans'], 1,
    '1071 Malazgirt Savaşı’nda Sultan Alparslan komutasındaki Büyük Selçuklu ordusu Bizans’ı yenmiş, Anadolu’nun kapıları Türklere açılmıştır.'],
  ['osmanli-kurulus', 'Osmanlı Devleti’nde ilk düzenli ordu olan Yeniçeri Ocağı hangi padişah döneminde kurulmuştur?',
    ['Osman Bey', 'Orhan Bey', 'I. Murat', 'Yıldırım Bayezid', 'Çelebi Mehmet'], 2,
    'Kapıkulu Ocakları ve Yeniçeri Ocağı I. Murat döneminde, devşirme sistemine dayalı olarak kurulmuştur.'],
  ['osmanli-yukselme', 'İstanbul’un fethi (1453) sonrası aşağıdakilerden hangisi doğrudan gerçekleşmiştir?',
    ['Kapitülasyonların kaldırılması', 'Orta Çağ’ın sona ermesi', 'Osmanlı’nın Batılılaşma döneminin başlaması', 'Karlofça Antlaşması’nın imzalanması', 'Tanzimat Fermanı’nın ilanı'], 1,
    'İstanbul’un fethi Orta Çağ’ın sonu, Yeni Çağ’ın başlangıcı kabul edilir.'],
  ['osmanli-dagilma', 'Osmanlı Devleti’nin toprak kaybettiği ilk antlaşma olarak kabul edilen antlaşma hangisidir?',
    ['Karlofça Antlaşması', 'Pasarofça Antlaşması', 'Küçük Kaynarca Antlaşması', 'Zitvatorok Antlaşması', 'Belgrat Antlaşması'], 0,
    '1699 Karlofça Antlaşması, Osmanlı’nın Batı’da büyük ölçüde toprak kaybettiği ilk antlaşmadır.'],
  ['kurtulus-savasi', 'Kurtuluş Savaşı’nda TBMM ordusunun ilk askerî zaferi aşağıdakilerden hangisidir?',
    ['I. İnönü Muharebesi', 'Sakarya Meydan Muharebesi', 'Büyük Taarruz', 'Kütahya-Eskişehir Muharebeleri', 'Çanakkale Savaşı'], 0,
    'TBMM ordularının düzenli ordu olarak kazandığı ilk zafer I. İnönü Muharebesi’dir (Ocak 1921).'],
  ['kurtulus-savasi', 'Lozan Barış Antlaşması hangi tarihte imzalanmıştır?',
    ['30 Ağustos 1922', '11 Ekim 1922', '24 Temmuz 1923', '29 Ekim 1923', '20 Ocak 1921'], 2,
    'Lozan Barış Antlaşması 24 Temmuz 1923’te imzalanmıştır.'],
  ['inkilaplar', 'Saltanat aşağıdaki tarihlerin hangisinde kaldırılmıştır?',
    ['1 Kasım 1922', '29 Ekim 1923', '3 Mart 1924', '17 Şubat 1926', '10 Nisan 1928'], 0,
    'Saltanat 1 Kasım 1922’de TBMM kararıyla kaldırılmıştır. Halifelik ise 3 Mart 1924’te kaldırılmıştır.'],
  ['ataturk-ilkeleri', '“Egemenlik kayıtsız şartsız milletindir” ilkesi doğrudan hangi Atatürk ilkesiyle ilgilidir?',
    ['Laiklik', 'Cumhuriyetçilik', 'Halkçılık', 'Devletçilik', 'İnkılapçılık'], 1,
    'Milletin kendi kendini yönetmesi esasına dayanan bu anlayış cumhuriyetçilik ilkesinin temelidir.'],

  // ---- COĞRAFYA ----
  ['cografi-konum', 'Türkiye’nin matematik konumu dikkate alındığında aşağıdakilerden hangisi söylenemez?',
    ['Dört mevsim belirgin yaşanır.', 'Orta kuşakta yer alır.', 'Yerel saat farkı doğu-batı arasında 76 dakikadır.', 'Kuzey Yarım Küre’dedir.', 'Ekvator üzerinde yer alır.'], 4,
    'Türkiye 36°-42° kuzey enlemleri arasındadır; Ekvator üzerinde değildir.'],
  ['yer-sekilleri', 'Türkiye’nin en yüksek dağı ve yüksekliği aşağıdakilerden hangisidir?',
    ['Erciyes Dağı - 3917 m', 'Süphan Dağı - 4058 m', 'Ağrı Dağı - 5137 m', 'Cilo (Reşko) - 4135 m', 'Uludağ - 2543 m'], 2,
    'Ağrı Dağı 5137 m ile Türkiye’nin en yüksek noktasıdır.'],
  ['yer-sekilleri', 'Türkiye’nin en büyük gölü hangisidir?',
    ['Tuz Gölü', 'Beyşehir Gölü', 'Eğirdir Gölü', 'Van Gölü', 'İznik Gölü'], 3,
    'Van Gölü yaklaşık 3713 km² yüzölçümüyle Türkiye’nin en büyük gölüdür.'],
  ['yer-sekilleri', 'Türkiye’nin en uzun akarsuyu hangisidir?',
    ['Fırat', 'Sakarya', 'Kızılırmak', 'Yeşilırmak', 'Dicle'], 2,
    'Kaynağını ve ağzını Türkiye sınırları içinde bulunduran en uzun akarsu Kızılırmak’tır (yaklaşık 1355 km).'],
  ['iklim', 'Karadeniz ikliminin en belirgin özelliği aşağıdakilerden hangisidir?',
    ['Yazları sıcak ve kurak geçmesi', 'Her mevsim yağışlı olması', 'Kışların çok sert geçmesi', 'Yıllık yağışın 300 mm’nin altında olması', 'Bitki örtüsünün bozkır olması'], 1,
    'Karadeniz ikliminde her mevsim yağışlıdır; doğal bitki örtüsü ormandır.'],
  ['nufus-yerlesme', 'Türkiye’de nüfus yoğunluğunun en az olduğu bölge hangisidir?',
    ['Marmara Bölgesi', 'Ege Bölgesi', 'Doğu Anadolu Bölgesi', 'İç Anadolu Bölgesi', 'Akdeniz Bölgesi'], 2,
    'Yükseltinin fazla, iklimin sert ve iş imkânlarının sınırlı olması nedeniyle Doğu Anadolu en seyrek nüfuslu bölgedir.'],
  ['tarim-hayvancilik', 'Aşağıdaki ürünlerden hangisi Akdeniz ikliminin görüldüğü yerlerde yetiştirilir?',
    ['Çay', 'Fındık', 'Muz', 'Şeker pancarı', 'Keten'], 2,
    'Muz, kışları ılık geçen Akdeniz kıyılarında (özellikle Anamur-Alanya çevresi) yetiştirilir.'],
  ['madenler-enerji', 'Türkiye’de taş kömürü çıkarılan başlıca havza aşağıdakilerden hangisidir?',
    ['Soma', 'Zonguldak', 'Elbistan', 'Tunçbilek', 'Yatağan'], 1,
    'Taş kömürü Zonguldak havzasından; linyit ise Soma, Elbistan, Tunçbilek gibi sahalardan çıkarılır.'],
  ['ulasim-turizm', 'Kapadokya’nın peribacaları hangi süreçlerin sonucunda oluşmuştur?',
    ['Buzul aşındırması', 'Volkanik tüflerin akarsu ve rüzgârla aşındırılması', 'Karstik erime', 'Kıvrılma ve kırılma', 'Deltalaşma'], 1,
    'Volkanik tüf ve ignimbiritlerin akarsu, yağmur ve rüzgâr aşındırmasıyla şekillenmesi peribacalarını oluşturmuştur.'],

  // ---- VATANDAŞLIK ----
  ['hukuk-baslangic', 'Kamu hukuku dalları arasında aşağıdakilerden hangisi yer almaz?',
    ['Anayasa hukuku', 'İdare hukuku', 'Ceza hukuku', 'Borçlar hukuku', 'Vergi hukuku'], 3,
    'Borçlar hukuku özel hukuk dalıdır; diğerleri kamu hukuku dallarındandır.'],
  ['anayasa-tarihi', 'Türk tarihinin ilk yazılı anayasası aşağıdakilerden hangisidir?',
    ['Sened-i İttifak', 'Tanzimat Fermanı', 'Kanun-i Esasi', 'Teşkilat-ı Esasiye', '1924 Anayasası'], 2,
    '1876’da ilan edilen Kanun-i Esasi ilk yazılı Osmanlı-Türk anayasasıdır.'],
  ['temel-haklar', '1982 Anayasası’na göre temel hak ve hürriyetler hangi durumda kısmen veya tamamen durdurulabilir?',
    ['Ekonomik krizde', 'Savaş, seferberlik veya olağanüstü hâllerde', 'Genel seçim döneminde', 'Bütçe görüşmelerinde', 'Yerel seçimlerde'], 1,
    'Anayasa’nın 15. maddesine göre savaş, seferberlik veya olağanüstü hâllerde temel hak ve hürriyetlerin kullanılması kısmen veya tamamen durdurulabilir.'],
  ['yasama', 'Türkiye Büyük Millet Meclisi kaç milletvekilinden oluşur?',
    ['450', '500', '550', '600', '650'], 3,
    '2017 Anayasa değişikliğiyle milletvekili sayısı 600’e çıkarılmıştır.'],
  ['yasama', 'Milletvekili seçilebilmek için gerekli en düşük yaş kaçtır?',
    ['18', '20', '21', '25', '30'], 0,
    '2017 değişikliğiyle milletvekili seçilme yaşı 18’e indirilmiştir.'],
  ['yurutme', 'Cumhurbaşkanının görev süresi ve seçilebileceği dönem sayısı aşağıdakilerden hangisidir?',
    ['4 yıl - 2 dönem', '5 yıl - 2 dönem', '5 yıl - 1 dönem', '7 yıl - 1 dönem', '6 yıl - 2 dönem'], 1,
    'Cumhurbaşkanı 5 yıllığına seçilir ve bir kişi en fazla iki dönem cumhurbaşkanı seçilebilir.'],
  ['yargi', 'Anayasa Mahkemesi’nin görevleri arasında aşağıdakilerden hangisi yer almaz?',
    ['Kanunların anayasaya uygunluğunu denetlemek', 'Bireysel başvuruları karara bağlamak', 'Siyasi partilerin kapatılması davalarına bakmak', 'Adli yargıda son inceleme mercii olmak', 'Yüce Divan sıfatıyla yargılama yapmak'], 3,
    'Adli yargıda son inceleme mercii Yargıtay’dır; Anayasa Mahkemesi’nin böyle bir görevi yoktur.'],
  ['idare', 'Aşağıdakilerden hangisi yerinden yönetim (mahalli idare) kuruluşlarından biri değildir?',
    ['İl özel idaresi', 'Belediye', 'Köy', 'Valilik', 'Büyükşehir belediyesi'], 3,
    'Valilik, merkezi idarenin taşra teşkilatıdır; mahalli idare değildir.'],

  // ---- GÜNCEL ----
  ['kuruluslar', 'Türkiye NATO’ya hangi yıl üye olmuştur?',
    ['1945', '1949', '1952', '1963', '1974'], 2,
    'Türkiye, Yunanistan ile birlikte 18 Şubat 1952’de NATO üyesi olmuştur.'],
  ['kuruluslar', 'Birleşmiş Milletler Güvenlik Konseyi’nin veto hakkına sahip daimî üye sayısı kaçtır?',
    ['3', '5', '7', '10', '15'], 1,
    'ABD, Rusya, Çin, Fransa ve Birleşik Krallık daimî üyedir ve veto hakkına sahiptir.'],
  ['kultur-sanat', 'UNESCO Dünya Mirası Listesi’ne alınan Göbeklitepe hangi ilimizdedir?',
    ['Mardin', 'Şanlıurfa', 'Diyarbakır', 'Gaziantep', 'Adıyaman'], 1,
    'Göbeklitepe Şanlıurfa’da yer alır ve 2018’de UNESCO Dünya Mirası Listesi’ne alınmıştır.'],
  ['turkiye-guncel', 'Türkiye’nin ilk yerli otomobil markası aşağıdakilerden hangisidir?',
    ['Anadol', 'TOGG', 'Devrim', 'Otosan', 'Murat'], 1,
    'TOGG, Türkiye’nin Otomobili Girişim Grubu tarafından üretilen yerli elektrikli otomobil markasıdır. (Devrim ise 1961’de üretilen ilk yerli otomobil prototipidir.)'],
  ['turkiye-guncel', 'Türkiye’nin ilk nükleer güç santrali hangi ilimizde inşa edilmektedir?',
    ['Sinop', 'Mersin', 'Kırklareli', 'Adana', 'İğneada'], 1,
    'Akkuyu Nükleer Güç Santrali Mersin’in Gülnar ilçesinde inşa edilmektedir.'],

  // ---- EĞİTİM BİLİMLERİ ----
  ['gelisim', 'Piaget’nin bilişsel gelişim kuramına göre "korunum" kazanımı hangi dönemde gerçekleşir?',
    ['Duyusal motor dönem', 'İşlem öncesi dönem', 'Somut işlemler dönemi', 'Soyut işlemler dönemi', 'Sezgisel dönem'], 2,
    'Korunum (miktarın görünüm değişse de sabit kalması) somut işlemler döneminde (7-11 yaş) kazanılır.'],
  ['gelisim', 'Erikson’un psikososyal gelişim kuramında ergenlik dönemine karşılık gelen çatışma aşağıdakilerden hangisidir?',
    ['Güvene karşı güvensizlik', 'Girişkenliğe karşı suçluluk', 'Başarıya karşı aşağılık duygusu', 'Kimlik kazanmaya karşı kimlik karmaşası', 'Üretkenliğe karşı durgunluk'], 3,
    'Ergenlik (12-18 yaş) dönemi "kimlik kazanma - kimlik karmaşası" çatışmasıyla tanımlanır.'],
  ['ogrenme', 'Bir öğrencinin sınavdan yüksek not alınca daha çok çalışmaya başlaması hangi kavramla açıklanır?',
    ['Olumsuz pekiştirme', 'Olumlu pekiştirme', 'Ceza', 'Sönme', 'Genelleme'], 1,
    'Davranışın ardından hoşa giden bir uyarıcı verilerek davranışın sıklığının artması olumlu pekiştirmedir.'],
  ['ogrenme', 'Pavlov’un klasik koşullanma deneyinde zil sesi başlangıçta hangi uyarıcıdır?',
    ['Koşulsuz uyarıcı', 'Koşullu uyarıcı', 'Nötr uyarıcı', 'Pekiştireç', 'Ayırt edici uyarıcı'], 2,
    'Zil sesi koşullanma öncesinde tepki doğurmayan nötr uyarıcıdır; eşleştirme sonrası koşullu uyarıcıya dönüşür.'],
  ['program', 'Eğitim programının ögeleri aşağıdakilerin hangisinde birlikte ve doğru verilmiştir?',
    ['Hedef - içerik - eğitim durumları - sınama durumları', 'Hedef - yöntem - araç - ölçme', 'Amaç - konu - öğretmen - öğrenci', 'Giriş - gelişme - sonuç - değerlendirme', 'Plan - uygulama - kontrol - önlem'], 0,
    'Program geliştirmede dört temel öge: hedef, içerik, eğitim durumları ve sınama (değerlendirme) durumlarıdır.'],
  ['yontem-teknik', 'Bir konunun uzman kişilerce dinleyici önünde tartışıldığı, başkanın yönettiği teknik aşağıdakilerden hangisidir?',
    ['Beyin fırtınası', 'Panel', 'Münazara', 'Rol oynama', 'Altı şapkalı düşünme'], 1,
    'Panelde konunun uzmanları, izleyici önünde ve bir başkan yönetiminde sohbet havasında konuyu tartışır.'],
  ['olcme', 'Bir ölçme aracının ölçmek istediği özelliği başka özelliklerle karıştırmadan ölçmesine ne denir?',
    ['Güvenirlik', 'Geçerlik', 'Kullanışlılık', 'Objektiflik', 'Duyarlık'], 1,
    'Geçerlik, aracın ölçmeyi amaçladığı özelliği doğru biçimde ölçmesidir.'],
  ['rehberlik', 'Rehberliğin temel ilkeleri arasında aşağıdakilerden hangisi yer almaz?',
    ['Gizlilik', 'Gönüllülük', 'Süreklilik', 'Zorunluluk', 'Bireye saygı'], 3,
    'Rehberlik hizmetleri gönüllülük esasına dayanır; zorunluluk bir ilke değildir.'],
  ['sinif-yonetimi', 'Sınıf kurallarının belirlenmesinde en uygun yaklaşım aşağıdakilerden hangisidir?',
    ['Öğretmen tek başına belirlemeli', 'Okul yönetimi belirlemeli', 'Öğrencilerle birlikte belirlenmeli', 'Veliler belirlemeli', 'Kurala gerek yoktur'], 2,
    'Öğrencilerin katılımıyla belirlenen kurallar benimsenme ve uyulma olasılığı en yüksek olanlardır.'],
]

/* [konuId, ön yüz, arka yüz] */
export const KARTLAR = [
  ['ses-bilgisi', 'Ünsüz benzeşmesi nedir?', 'Sert ünsüzle biten sözcüğe yumuşak ünsüzle başlayan ek geldiğinde ekin sertleşmesidir: "sokak-da → sokakta". #SesBilgisi #Benzesme'],
  ['yazim-kurallari', '"de/da" ne zaman ayrı yazılır?', 'Bağlaç olan "de/da" ayrı yazılır ve "dahi, bile" anlamı taşır: "Sen de gel." Hâl eki olan "-de/-da" bitişik yazılır: "Evde kaldı." #Yazim'],
  ['noktalama', 'Noktalı virgül (;) nerede kullanılır?', 'Ögeleri arasında virgül bulunan sıralı cümleleri ve aynı türden grupları ayırmak için kullanılır. #Noktalama'],
  ['cumlenin-ogeleri', 'Cümlenin temel ögeleri nelerdir?', 'Yüklem ve özne temel ögelerdir. Nesne, dolaylı tümleç ve zarf tümleci yardımcı ögelerdir. #Ogeler'],
  ['temel-kavramlar', 'Ardışık sayılar toplamı formülü', 'İlk n doğal sayının toplamı: n(n+1)/2. İlk n tek sayının toplamı: n². #Matematik #Formul'],
  ['ebob-ekok', 'EBOB ve EKOK ilişkisi', 'İki sayı için: EBOB(a,b) × EKOK(a,b) = a × b. #EBOB #EKOK'],
  ['olasilik', 'Permütasyon ve kombinasyon farkı', 'Permütasyonda sıralama önemlidir P(n,r)=n!/(n−r)!; kombinasyonda önemli değildir C(n,r)=n!/(r!(n−r)!). #Olasilik'],
  ['islamiyet-oncesi', 'Kavimler Göçü', '375 yılında Batı Hunlarının baskısıyla başlayan göç dalgası, Roma İmparatorluğu’nun ikiye ayrılmasına ve Orta Çağ’ın başlamasına zemin hazırladı. #Tarih #KavimlerGocu'],
  ['osmanli-kurulus', 'Osmanlı’nın kuruluşu', 'Osmanlı Beyliği 1299’da Söğüt ve çevresinde Osman Bey tarafından kuruldu. İlk başkent Söğüt, ardından Bursa oldu. #Osmanli'],
  ['osmanli-yukselme', 'Fatih Sultan Mehmet dönemi', 'İstanbul’un fethi (1453), Otlukbeli Savaşı (1473), Trabzon ve Kırım’ın alınması bu dönemdedir. #Fatih'],
  ['kurtulus-savasi', 'Kurtuluş Savaşı cepheleri', 'Doğu Cephesi (Kâzım Karabekir - Ermeniler), Güney Cephesi (Fransızlar, düzenli ordu kurulmadan), Batı Cephesi (Yunanlılar). #KurtulusSavasi'],
  ['inkilaplar', 'Harf İnkılabı', '1 Kasım 1928’de Yeni Türk Alfabesi kabul edildi; okuma yazma seferberliği için Millet Mektepleri açıldı. #Inkilap'],
  ['yer-sekilleri', 'Türkiye’nin uç noktaları', 'Kuzey: Sinop-İnceburun, Güney: Hatay-Beysun, Doğu: Iğdır-Dilucu, Batı: Çanakkale-Avlaka Burnu. #Cografya'],
  ['iklim', 'Türkiye’de görülen iklim tipleri', 'Akdeniz iklimi, Karadeniz iklimi ve Karasal iklim. Her birinin farklı bitki örtüsü vardır: maki, orman, bozkır. #Iklim'],
  ['madenler-enerji', 'Bor madeni', 'Türkiye dünya bor rezervlerinin büyük bölümüne sahiptir. Başlıca sahalar: Eskişehir-Kırka, Balıkesir-Bigadiç, Kütahya-Emet, Bursa-Kestelek. #Maden'],
  ['temel-haklar', 'Kişi hakları', 'Yaşama hakkı, kişi dokunulmazlığı, özel hayatın gizliliği, konut dokunulmazlığı, haberleşme hürriyeti kişi haklarındandır. #Vatandaslik'],
  ['yargi', 'Yüksek mahkemeler', 'Anayasa Mahkemesi, Yargıtay, Danıştay, Uyuşmazlık Mahkemesi. #Yargi'],
  ['yurutme', 'Cumhurbaşkanlığı kararnamesi', 'Cumhurbaşkanı, yürütme yetkisine ilişkin konularda kararname çıkarabilir; temel haklar, kişi hakları ve siyasi haklar bu yolla düzenlenemez. #Yurutme'],
  ['gelisim', 'Kohlberg ahlak gelişimi', 'Gelenek öncesi, geleneksel ve gelenek sonrası olmak üzere 3 düzey ve 6 evre vardır. #EgitimBilimleri'],
  ['ogrenme', 'Bloom taksonomisi (yenilenmiş)', 'Hatırlama, anlama, uygulama, çözümleme, değerlendirme, yaratma. #Bloom'],
  ['olcme', 'Geçerlik ve güvenirlik ilişkisi', 'Geçerli bir test mutlaka güvenilirdir; ancak güvenilir her test geçerli olmayabilir. #Olcme'],
]

/* [ifade, doğru mu, açıklama] */
export const DOGRUMU = [
  ['Türkiye’nin en büyük gölü Tuz Gölü’dür.', false, 'Türkiye’nin en büyük gölü Van Gölü’dür.'],
  ['İstanbul’un fethi 1453 yılında gerçekleşmiştir.', true, 'Fatih Sultan Mehmet 29 Mayıs 1453’te İstanbul’u fethetmiştir.'],
  ['Saltanat, halifelikten önce kaldırılmıştır.', true, 'Saltanat 1 Kasım 1922’de, halifelik 3 Mart 1924’te kaldırılmıştır.'],
  ['Ağrı Dağı volkanik bir dağdır.', true, 'Ağrı Dağı sönmüş bir volkandır ve Türkiye’nin en yüksek noktasıdır.'],
  ['TBMM 550 milletvekilinden oluşur.', false, '2017 Anayasa değişikliğinden sonra milletvekili sayısı 600’dür.'],
  ['Kızılırmak Türkiye’nin en uzun akarsuyudur.', true, 'Kızılırmak yaklaşık 1355 km ile en uzun akarsuyumuzdur.'],
  ['Borçlar hukuku bir kamu hukuku dalıdır.', false, 'Borçlar hukuku özel hukuk dalıdır.'],
  ['Karadeniz ikliminde her mevsim yağış görülür.', true, 'Karadeniz ikliminin en belirgin özelliği her mevsim yağışlı olmasıdır.'],
  ['Orhun Yazıtları Uygurlar döneminde dikilmiştir.', false, 'Orhun Yazıtları II. Göktürk (Kutluk) Devleti döneminde dikilmiştir.'],
  ['Lozan Antlaşması 24 Temmuz 1923’te imzalanmıştır.', true, 'Lozan Barış Antlaşması bu tarihte imzalanmış ve Türkiye’nin bağımsızlığı tescillenmiştir.'],
  ['Türkiye NATO’ya 1949’da kurucu üye olarak katılmıştır.', false, 'Türkiye NATO’ya 1952’de üye olmuştur; kurucu üye değildir.'],
  ['Erikson’a göre ergenlik dönemi çatışması "kimlik kazanma - kimlik karmaşası"dır.', true, 'Erikson’un psikososyal kuramında 12-18 yaş bu çatışmayla tanımlanır.'],
  ['Geçerli bir ölçme aracı mutlaka güvenilirdir.', true, 'Geçerlik güvenirliği gerektirir; tersi her zaman doğru değildir.'],
  ['Taş kömürü Türkiye’de en çok Soma’dan çıkarılır.', false, 'Soma linyit sahasıdır; taş kömürü Zonguldak havzasından çıkarılır.'],
  ['Malazgirt Savaşı 1071’de yapılmıştır.', true, 'Sultan Alparslan komutasındaki Büyük Selçuklu ordusu Bizans’ı yenmiştir.'],
  ['Anayasa Mahkemesi adli yargıda son inceleme merciidir.', false, 'Adli yargıda son inceleme mercii Yargıtay’dır.'],
  ['Göbeklitepe Şanlıurfa’dadır.', true, '2018’de UNESCO Dünya Mirası Listesi’ne alınmıştır.'],
  ['Kapadokya’daki peribacaları buzul aşındırmasıyla oluşmuştur.', false, 'Volkanik tüflerin akarsu, yağmur ve rüzgârla aşındırılmasıyla oluşmuştur.'],
]

/* [olay, yıl] */
export const KRONOLOJI = [
  ['Kavimler Göçü', 375],
  ['Göktürk Devleti’nin kuruluşu', 552],
  ['Talas Savaşı', 751],
  ['Malazgirt Savaşı', 1071],
  ['Miryokefalon Savaşı', 1176],
  ['Kösedağ Savaşı', 1243],
  ['Osmanlı Beyliği’nin kuruluşu', 1299],
  ['Koyunhisar Savaşı', 1302],
  ['I. Kosova Savaşı', 1389],
  ['Ankara Savaşı', 1402],
  ['İstanbul’un Fethi', 1453],
  ['Otlukbeli Savaşı', 1473],
  ['Çaldıran Savaşı', 1514],
  ['Mohaç Meydan Muharebesi', 1526],
  ['Preveze Deniz Zaferi', 1538],
  ['İnebahtı (Lepanto) Deniz Savaşı', 1571],
  ['Zitvatorok Antlaşması', 1606],
  ['Karlofça Antlaşması', 1699],
  ['Pasarofça Antlaşması', 1718],
  ['Küçük Kaynarca Antlaşması', 1774],
  ['Sened-i İttifak', 1808],
  ['Tanzimat Fermanı', 1839],
  ['Islahat Fermanı', 1856],
  ['I. Meşrutiyet (Kanun-i Esasi)', 1876],
  ['II. Meşrutiyet', 1908],
  ['Trablusgarp Savaşı’nın başlaması', 1911],
  ['Balkan Savaşları’nın başlaması', 1912],
  ['Çanakkale Savaşları', 1915],
  ['Mondros Ateşkes Antlaşması', 1918],
  ['Amasya Genelgesi', 1919],
  ['TBMM’nin açılışı', 1920],
  ['Sakarya Meydan Muharebesi', 1921],
  ['Büyük Taarruz ve Başkomutanlık Meydan Muharebesi', 1922],
  ['Lozan Barış Antlaşması', 1923],
  ['Cumhuriyet’in ilanı', 1923],
  ['Halifeliğin kaldırılması', 1924],
  ['Şapka Kanunu', 1925],
  ['Türk Medeni Kanunu’nun kabulü', 1926],
  ['Harf İnkılabı', 1928],
  ['Kadınlara milletvekili seçme ve seçilme hakkı', 1934],
  ['Soyadı Kanunu', 1934],
  ['Hatay’ın anavatana katılması', 1939],
]

/* [sol, sağ] */
export const ESLESTIRME = [
  ['Malazgirt Savaşı', '1071'],
  ['Türk Medeni Kanunu', '1926'],
  ['Türkiye’nin en yüksek dağı', 'Ağrı Dağı'],
  ['Türkiye’nin en büyük gölü', 'Van Gölü'],
  ['Taş kömürü havzası', 'Zonguldak'],
  ['İlk yazılı Türk anayasası', 'Kanun-i Esasi'],
  ['Bilişsel gelişim kuramı', 'Piaget'],
  ['Psikososyal gelişim kuramı', 'Erikson'],
  ['Klasik koşullanma', 'Pavlov'],
  ['Ahlak gelişimi kuramı', 'Kohlberg'],
  ['Orhun Yazıtları', 'II. Göktürk Devleti'],
  ['Kavimler Göçü', '375'],
  ['NATO üyeliği', '1952'],
  ['Göbeklitepe', 'Şanlıurfa'],
  ['Akkuyu Nükleer Santrali', 'Mersin'],
  ['Peribacaları', 'Kapadokya'],
  ['En uzun akarsu', 'Kızılırmak'],
  ['Bor madeni sahası', 'Eskişehir-Kırka'],
  ['Yeniçeri Ocağı’nın kurulması', 'I. Murat'],
  ['İlk toprak kaybı antlaşması', 'Karlofça'],
]

export const BILGILER = [
  ['Türkiye’nin en uzun akarsuyu Kızılırmak’tır (yaklaşık 1355 km) ve tamamı Türkiye sınırları içindedir.', 'Coğrafya'],
  ['Türkiye’de saat farkı doğu-batı arasında yaklaşık 76 dakikadır; bu, 19 boylam farkından kaynaklanır.', 'Coğrafya'],
  ['Osmanlı’da ilk kez matbaa 1727’de İbrahim Müteferrika tarafından kurulmuştur.', 'Tarih'],
  ['Cumhuriyet tarihinde kadınlara milletvekili seçme ve seçilme hakkı 1934’te tanınmıştır — birçok Avrupa ülkesinden önce.', 'Tarih'],
  ['"Yalnız" ve "yanlız" karıştırılır; doğru yazım "yalnız"dır.', 'Türkçe'],
  ['Ardışık ilk n tek sayının toplamı her zaman n²’dir: 1+3+5+7 = 16 = 4².', 'Matematik'],
  ['1982 Anayasası’nın ilk üç maddesi değiştirilemez ve değiştirilmesi teklif edilemez.', 'Vatandaşlık'],
  ['Van Gölü sodalı yapısıyla dünyanın en büyük sodalı gölüdür.', 'Coğrafya'],
  ['Türkiye dünyadaki bilinen bor rezervlerinin büyük bölümüne sahiptir.', 'Coğrafya'],
  ['Piaget’ye göre "korunum" kazanımı somut işlemler döneminde (7-11 yaş) gerçekleşir.', 'Eğitim Bilimleri'],
  ['Ölçmede geçerlik güvenirliği gerektirir; ama güvenilir her araç geçerli değildir.', 'Eğitim Bilimleri'],
  ['Göktürkler, "Türk" adını devlet adı olarak kullanan ilk Türk devletidir.', 'Tarih'],
  ['Türkiye’nin en uzun kara sınırı Suriye iledir (yaklaşık 900 km).', 'Coğrafya'],
  ['Noktalı virgül, ögeleri arasında virgül bulunan sıralı cümleleri ayırmak için kullanılır.', 'Türkçe'],
  ['KPSS’de 4 yanlış 1 doğruyu götürür; net = doğru − yanlış/4.', 'Sınav'],
]

/* Denemeler: hangi konulardan kaç soru alınacağı */
export const DENEMELER = [
  {
    id: 'gy-deneme-1',
    ad: 'Genel Yetenek Denemesi 1',
    tur: 'genel',
    sure: 35,
    puanTuru: 'P3',
    renk: '#2a78d6',
    aciklama: 'Türkçe ve Matematik karışık',
    bolumler: [
      { dersId: 'turkce', ad: 'Türkçe' },
      { dersId: 'matematik', ad: 'Matematik' },
    ],
  },
  {
    id: 'gk-deneme-1',
    ad: 'Genel Kültür Denemesi 1',
    tur: 'genel',
    sure: 35,
    puanTuru: 'P3',
    renk: '#1baf7a',
    aciklama: 'Tarih, Coğrafya, Vatandaşlık ve Güncel Bilgiler',
    bolumler: [
      { dersId: 'tarih', ad: 'Tarih' },
      { dersId: 'cografya', ad: 'Coğrafya' },
      { dersId: 'vatandaslik', ad: 'Vatandaşlık' },
      { dersId: 'guncel', ad: 'Güncel Bilgiler' },
    ],
  },
  {
    id: 'tarih-brans-1',
    ad: 'Tarih Branş Denemesi 1',
    tur: 'brans',
    sure: 20,
    puanTuru: 'P3',
    renk: '#199e70',
    aciklama: 'Yalnızca Tarih soruları',
    bolumler: [{ dersId: 'tarih', ad: 'Tarih' }],
  },
  {
    id: 'eb-deneme-1',
    ad: 'Eğitim Bilimleri Denemesi 1',
    tur: 'brans',
    sure: 25,
    puanTuru: 'P10',
    renk: '#4a3aa7',
    aciklama: 'Gelişim, öğrenme, ölçme ve rehberlik',
    bolumler: [{ dersId: 'egitimbilimleri', ad: 'Eğitim Bilimleri' }],
  },
]
